[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

; Set the serial monitor speed
monitor_speed = 115200

; Compiler flags to enable native USB HID and CDC (Serial) on Boot
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D ARDUINO_USB_MSC_ON_BOOT=0
    -D ARDUINO_USB_DFU_ON_BOOT=0
    -D ARDUINO_USB_MODE=1

; This tells PlatformIO to compile ONLY main.cpp and ignore all other files in src/
src_filter = +<main.cpp> -<workwithit.cpp>
